### ISSUE TITLE
User can see their car

### ISSUE THREAD

**Issue by S-Chiaravanont** [S-Chiaravanont/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List
- [x] Create a background `div` that take 100% width & height of viewport.
- [x] Place a vehicle `img` on top of the background.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
