### ISSUE TITLE
User can turn their car

### ISSUE THREAD

**Issue by S-Chiaravanont** [S-Chiaravanont/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] Add `addEventListener()` to the `window` element to track when users press any key.
- [x] Query for the vehicle `img`.
- [x] Add `function` to rotate vehicle when arrow keys are pressed.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
