### ISSUE TITLE
User can start their car

### ISSUE THREAD

**Issue by S-Chiaravanont** [S-Chiaravanont/driving-game#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List
- [ ] Create data object to store vehicle's current value of `x` and `y` coordinates as `left` and `top`.
- [ ] Add new CSS style for vehicle `img` element and set `position: absolute;` as well as `left: 0; top: 0;` for starting point.
- [ ] Add a function `movement()` that increment value of `left` by 1 and update vehicle absolute position to match the new `left` value.
- [ ] Add a `setInterval()` that call on `movement()` every 16 milliseconds.
- [ ] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [ ] Test all functionality again in a private browsing session.
- [ ] Fix all errors.
